### ISSUE TITLE
Support vagrant deploy to aws

### ISSUE THREAD

**Issue by hahla** [pelias/vagrant#10]
I was being optimistic and tried to deploy to ec2 today (i.e. edited manually the default Vagrantfile). This ticket is to support this either by providing a vagrantfile support with an aws compatible box, or other method.

[ec2-user@ip-172-31-44-227 vagrant]$ vagrant up --provider=aws
Bringing machine 'default' up with 'aws' provider...
==> default: Box 'dummy' could not be found. Attempting to find and install...
    default: Box Provider: aws
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'dummy' (v0) for provider: aws
    default: Downloading: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
The box you attempted to add doesn't match the provider you specified.

Provider expected: aws
Provider of box: virtualbox

**Comment by heffergm** [comment]
I can provide a boilerplate change to Vagrantfile that shows roughly what this would look like, but obviously the configuration details are going to be specific to you (key names, ami, etc).

Something like:

```
  if ENV['PELIAS_AWS']
    # for this to work, please follow the instructions here: https://github.com/mitchellh/vagrant-aws
    config.vm.box         = 'dummy'
    aws.access_key_id     = 'YOUR KEY'
    aws.secret_access_key = 'YOUR SECRET KEY'
    aws.session_token     = 'SESSION TOKEN'
    aws.keypair_name      = 'KEYPAIR NAME'
    aws.ami               = 'ami-7747d01e'

    override.ssh.username = 'ubuntu'
    override.ssh.private_key_path = 'PATH TO YOUR PRIVATE KEY'
  else
    config.vm.box               = 'ubuntu-14.04-opscode'
    config.vm.box_url           = 'http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box'
  end
```

I think your only real issue above is that you need to change the box name to 'dummy' and create the dummy box as outlined here: https://github.com/mitchellh/vagrant-aws

**Comment by heffergm** [comment]
e.g.

```
PELIAS_AWS=true PELIAS_AWS_KEYPAIR_NAME=mapzen-ec2-us-east PELIAS_AWS_PRIVATE_KEY_PATH=/Users/grant/.ssh/mapzen_id_rsa AWS_ACCESS_KEY_ID=redacted AWS_SECRET_ACCESS_KEY=redacted vagrant up --provider=aws

==> default: Launching an instance with the following settings...
==> default:  -- Type: m3.medium
==> default:  -- AMI: ami-7747d01e
==> default:  -- Region: us-east-1
==> default:  -- Keypair: mapzen-ec2-us-east
==> default:  -- Block Device Mapping: []
==> default:  -- Terminate On Shutdown: false
==> default:  -- Monitoring: false
==> default:  -- EBS optimized: false
==> default:  -- Assigning a public IP address in a VPC: false
==> default: Waiting for instance to become "ready"...
==> default: Waiting for SSH to become available...
```

**Comment by heffergm** [comment]
I'll go ahead and merge these changes, but looking at the vagrant-aws plugin, the code appears rather stale. I've gotten this to mostly work, but there appear to be some ssh auth bugs that may or may not be particular to my setup. Give it a whirl though and let me know.

**Comment by riordan** [comment]
Awesome - @hahla let us know how it's working for you!

**Comment by abuzakaria** [comment]
Is there a way to fix the following error?

> /.vagrant.d/gems/gems/excon-0.49.0/lib/excon/middlewares/expects.rb:6:in 'response_call': The image id '[ami-7747d01e]' does not exist (Fog::Compute::AWS::NotFound)

thanks
