### ISSUE TITLE
NYC sample dataset import fails

### ISSUE THREAD

**Issue by amiller2978** [pelias/vagrant#15]
I get the following error when trying to import the NYC dataset. I've verified that the files exist, permissions, etc. Any suggestions?

vagrant@pelias:~/openaddresses$ node import.js ../my_dataset
/home/vagrant/openaddresses/import.js:181
    var configFiles = peliasConfig.imports.openaddresses.files;
                                                        ^
TypeError: Cannot read property 'files' of undefined
    at Object.<anonymous> (/home/vagrant/openaddresses/import.js:181:57)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by orangejulius** [comment]
Howdy,
Nice catch! Looks like this was a bug where we weren't properly handling the case where there isn't anything in pelias.json for openaddresses (we rarely do that ourselves but do claim to support it). I've put a potential fix in the branch at https://github.com/pelias/openaddresses/tree/fix-cli-dir-handling, can you take a look and see if it fixes things?

Thanks!

**Comment by amillerBoundless** [comment]
I removed the openaddresses directory and then pulled the branch down(please verify I'm a gitnoob). 

I'm seeing the same issue. 

Thanks for the help, I'm looking forward to giving Pelias a try!

vagrant@pelias:~$ rm -rf openaddresses
vagrant@pelias:~$ git clone https://github.com/pelias/openaddresses.git
Cloning into 'openaddresses'...
remote: Counting objects: 343, done.
remote: Total 343 (delta 0), reused 0 (delta 0), pack-reused 343
Receiving objects: 100% (343/343), 61.06 KiB | 0 bytes/s, done.
Resolving deltas: 100% (186/186), done.
Checking connectivity... done.
vagrant@pelias:~$ cd openaddresses
vagrant@pelias:~/openaddresses$ npm install

> precommit-hook@1.0.7 install /home/vagrant/openaddresses/node_modules/precommit-hook
> hook_install

Creating .git/hooks/pre-commit...
npm WARN engine elasticsearch@2.4.3: wanted: {"node":">=0.8 <0.11"} (current: {"node":"0.12.7","npm":"2.11.3"})

> microtime@1.4.2 install /home/vagrant/openaddresses/node_modules/pelias-admin-lookup/node_modules/microtime
> node-gyp rebuild

make: Entering directory `/home/vagrant/openaddresses/node_modules/pelias-admin-lookup/node_modules/microtime/build'
  CXX(target) Release/obj.target/microtime/src/microtime.o
  SOLINK_MODULE(target) Release/obj.target/microtime.node
  COPY Release/microtime.node
make: Leaving directory `/home/vagrant/openaddresses/node_modules/pelias-admin-lookup/node_modules/microtime/build'
npm WARN prefer global jshint@2.5.11 should be installed with -g
precommit-hook@1.0.7 node_modules/precommit-hook

minimist@1.1.0 node_modules/minimist

pelias-model@0.3.0 node_modules/pelias-model

combined-stream@0.0.7 node_modules/combined-stream
└── delayed-stream@0.0.5

csv-parse@0.0.6 node_modules/csv-parse

through2@0.6.3 node_modules/through2
├── xtend@4.0.0
└── readable-stream@1.0.33 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)

pelias-config@0.1.6 node_modules/pelias-config
└── mergeable@0.0.0 (extend@1.3.0)

tap-spec@2.1.2 node_modules/tap-spec
├── duplexer@0.1.1
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── pretty-ms@1.4.0 (parse-ms@1.0.0, get-stdin@4.0.1, plur@1.0.0, is-finite@1.0.1, meow@3.3.0)
├── tap-parser@0.7.0 (inherits@2.0.1, minimist@0.2.0, readable-stream@1.1.13)
└── tap-out@1.3.2 (trim@0.0.1, re-emitter@1.1.1, split@1.0.0, readable-stream@2.0.2)

tape@3.0.3 node_modules/tape
├── inherits@2.0.1
├── defined@0.0.0
├── resumer@0.0.0
├── deep-equal@0.2.2
├── through@2.3.8
├── object-inspect@0.4.0
└── glob@3.2.11 (minimatch@0.3.0)

pelias-logger@0.0.8 node_modules/pelias-logger
└── winston@0.9.0 (cycle@1.0.3, stack-trace@0.0.9, eyes@0.1.8, isstream@0.1.2, pkginfo@0.3.0, async@0.9.2, colors@1.0.3)

pelias-address-deduplicator@1.0.6 node_modules/pelias-address-deduplicator
└── request@2.51.0 (caseless@0.8.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.5.0, tunnel-agent@0.4.1, json-stringify-safe@5.0.1, node-uuid@1.4.3, qs@2.3.3, mime-types@1.0.2, bl@0.9.4, http-signature@0.10.1, form-data@0.2.0, hawk@1.1.1, tough-cookie@2.0.0)

jshint@2.5.11 node_modules/jshint
├── strip-json-comments@1.0.4
├── underscore@1.6.0
├── exit@0.1.2
├── console-browserify@1.1.0 (date-now@0.1.4)
├── minimatch@1.0.0 (sigmund@1.0.1, lru-cache@2.6.5)
├── shelljs@0.3.0
├── cli@0.6.6 (glob@3.2.11)
└── htmlparser2@3.8.3 (domelementtype@1.3.0, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.13, domutils@1.5.1)

pelias-dbclient@0.0.9 node_modules/pelias-dbclient
├── pelias-config@0.0.7 (mergeable@0.0.0)
├── openstreetmap-stream@0.0.6 (through2@0.5.1, stream-combiner2@1.0.2)
├── byline@4.2.1
├── osm-pbf-parser@2.1.2 (inherits@2.0.1, readable-stream@1.1.13, stream-combiner2@1.0.2, protocol-buffers@2.7.0, brfs@1.4.1)
└── elasticsearch@2.4.3 (forever-agent@0.5.2, chalk@0.5.1, bluebird@2.2.2, lodash-node@2.4.1)

pelias-admin-lookup@2.0.8 node_modules/pelias-admin-lookup
├── simplify-js@1.2.1
├── async@0.9.0
├── require-dir@0.2.0
├── polygon-lookup@1.0.2 (point-in-polygon@0.0.0, rbush@1.3.4)
├── microtime@1.4.2 (bindings@1.2.1, nan@1.8.4)
└── shapefile-stream@0.0.4 (through2@0.5.1, readable-stream@1.0.33, shapefile@0.3.0)
vagrant@pelias:~/openaddresses$ node import.js ../my_dataset
/home/vagrant/openaddresses/import.js:181
    var configFiles = peliasConfig.imports.openaddresses.files;
                                                        ^
TypeError: Cannot read property 'files' of undefined
    at Object.<anonymous> (/home/vagrant/openaddresses/import.js:181:57)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
vagrant@pelias:~/openaddresses$ ls ../my_dataset/
us-ny-nyc.csv
vagrant@pelias:~/openaddresses$

**Comment by orangejulius** [comment]
Ah, you just missed checking out the branch. run "git checkout fix-cli-dir-handling" and let me know how it goes

**Comment by amillerBoundless** [comment]
Thanks...like I said git noob.  Progress, got a new error

vagrant@pelias:~$ cd openaddresses
vagrant@pelias:~/openaddresses$ git checkout fix-cli-dir-handling
Branch fix-cli-dir-handling set up to track remote branch fix-cli-dir-handling from origin.
Switched to a new branch 'fix-cli-dir-handling'
vagrant@pelias:~/openaddresses$ ls
import.js  lib  node_modules  package.json  README.md  test
vagrant@pelias:~/openaddresses$ node import.js ../my_dataset
module.js:338
    throw err;
          ^
Error: Cannot find module 'pelias-suggester-pipeline'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/vagrant/openaddresses/lib/import_pipelines.js:14:31)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
vagrant@pelias:~/openaddresses$

**Comment by orangejulius** [comment]
Hm, we might have updated some modules recently. npm install usually sorts out anything like that

**Comment by amillerBoundless** [comment]
Should I rerun the install?

**Comment by orangejulius** [comment]
yeah, if you didn't rerun "npm install" and then try the import again, do it.

**Comment by amillerBoundless** [comment]
Success!

vagrant@pelias:~$ cd openaddresses
vagrant@pelias:~/openaddresses$ npm install
pelias-suggester-pipeline@2.0.4 node_modules/pelias-suggester-pipeline
└── through2@0.5.1 (xtend@3.0.0, readable-stream@1.0.33)
vagrant@pelias:~/openaddresses$ node import.js ../my_dataset
2015-08-25T19:01:47.521Z - info: [openaddresses] Importing 1 files.
2015-08-25T19:01:47.845Z - info: [openaddresses] Creating read stream for:
../my_dataset/us-ny-nyc.csv
2015-08-25T19:03:50.475Z - info: [openaddresses] Total time taken: 122.617s
vagrant@pelias:~/openaddresses$

Thanks again for the help!

Aaron

On Tue, Aug 25, 2015 at 12:43 PM, Julian Simioni <notifications@github.com>
wrote:

> yeah, if you didn't rerun "npm install" and then try the import again, do
> it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pelias/vagrant/issues/15#issuecomment-134697704>.
>



-- 
Aaron Miller
Solution Engineer Boundless <http://boundlessgeo.com/>
M: 303-709-9005 | amiller@boundlessgeo.com

**Comment by orangejulius** [comment]
Awesome! Let us know how it goes from here!
