### ISSUE TITLE
elastic search scripts are downloaded, but not installed or symlinked into place

### ISSUE THREAD

**Issue by JesseCrocker** [pelias/vagrant#20]
Based on https://github.com/pelias/scripts#pelias-scripts I would expect to find the scripts in `/usr/local/elasticsearch/config/` but after setting up the vagrant enviroment the only files in that directory are elasticsearch.yml  and logging.yml.

The scripts are at `/opt/pelias/groovy/pelias-scripts/current/scripts/`

**Comment by riordan** [comment]
Luckily they haven't been needed. Vestigial code, signs of the project's evolution. We removed it from the project source last week and pull request #21 removed it from the Vagrant codebase.

**Comment by riordan** [comment]
@jessecrocker thanks for flagging this!
