### ISSUE TITLE
Update pelias_settings.example.rb to import OSM + OpenAddresses data with administrative hierarchy lookup

### ISSUE THREAD

**Issue by riordan** [pelias/vagrant#22]
The [pelias_settings.example.rb](https://github.com/pelias/vagrant/blob/master/pelias_settings.example.rb) file controls how Pelias builds its index.

When the setting `"adminLookup": true` is used for a dataset in `pelias_settings.rb`, it triggers our hierarchy normalization through the [administrative hierarchy lookup tool](https://github.com/pelias/admin-lookup) that normalizes the country, region (state/province), locality (city/state), and local administrative areas.

This is a feature several vagrant users have asked about over email, but I've had poor luck working through myself. Perhaps someone from the team could use their local environment's config as a default.
- [ ] add `adminLookup` by default to OSM + OpenAddresses imports
- [ ] add `adminLookup` documentation to README.MD.

**Comment by missinglink** [comment]
I believe this is a technical issue, maybe @heffergm can confirm. My understanding is that loading quattroshapes in memory to perform the lookups requires ~8GB of RAM which most virtual machines will not be capable of.

I think that this is disabled in order to prevent segfault errors

**Comment by missinglink** [comment]
I actually have a cunning plan which may be able to fix this @riordan let's discuss at our next 1:1

**Comment by heffergm** [comment]
Loading quattro into memory on a typical vagrant setup (or even a very atypical one) is not feasible, as noted.

**Comment by riordan** [comment]
Even though it's very rare, could we put an example of this config somewhere?

**Comment by orangejulius** [comment]
The vagrant image isn't used any longer, but we will be enabling admin lookup by default for all users very soon, as part of https://github.com/pelias/config/pull/52

**Comment by jeffbyrnes** [comment]
@orangejulius curious, how are you handling config mgmt. for pelias, if vagrant is no longer the preferred method?

**Comment by orangejulius** [comment]
We use chef internally, but it uses a completely separate set of scripts from the vagrant image. So while they started out similar, the vagrant image (which no one on the Pelias team actually ever used day to day) quickly grew out of date. Currently there is no publicly available config management option for Pelias, although we want to fix that someday.

**Comment by jeffbyrnes** [comment]
@orangejulius thanks! I had hoped as much. @darkskyapp is considering using Pelias for geocoding stuff, and I’d be happy to help with a community Chef cookbook at some point.
