### ISSUE TITLE
Default install legacyURL

### ISSUE THREAD

**Issue by rijvirajib** [pelias/vagrant#24]
Running a default install and attempting to use the test url http://localhost:3100/search?input=tower&lat=51.508079&lon=-0.076131 returns the following:

```json
{"error":"Invalid path, no legacy proxy specified"}
```

Admin URL: http://localhost:9200/
```json
{
  "status" : 200,
  "name" : "pelias",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.7.0",
    "build_hash" : "929b9739cae115e73c346cb5f9a6f24ba735a743",
    "build_timestamp" : "2015-07-16T14:31:07Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by rijvirajib** [comment]
Maybe we need to update the docs: http://localhost:3100/v1/search?text=London

**Comment by riordan** [comment]
@rijvirajib: thanks for finding this! We're still catching elements of the project that are impacted by our transition from the beta -> v1 of our API.

We certainly have to update the documentation here.

**Comment by riordan** [comment]
@rijvirajib would you be willing to submit a pull request for where this is?

There are plenty of places we haven't caught yet, but if you could help us identify this one, we'd be most appreciative.

**Comment by rijvirajib** [comment]
I'm actually going over the Readme and updating things as I see them.

**Comment by riordan** [comment]
Awesome; thank you so much!

On Wed, Oct 14, 2015 at 2:28 PM, Rijvi Rajib <notifications@github.com>
wrote:

> I'm actually going over the Readme and updating things as I see them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pelias/vagrant/issues/24#issuecomment-148145717>.
>



-- 
David Riordan | Product Manager - Search | dave.riordan@mapzen.com |
@riordan <https://twitter.com/riordan> | gpg 235D9DC95EF6277C
<https://keybase.io/riordan>
Mapzen | https://mapzen.com | @mapzen <https://twitter.com/search>
