### ISSUE TITLE
All Quattroshapes

### ISSUE THREAD

**Issue by rijvirajib** [pelias/vagrant#26]
I'm attempting to set up an entire-world reverse geocoder. To do this, I am using geonames with `alpha2_country_codes => [ 'all' ]` (do I have to manually add geonames zip file anywhere?), `openaddresses` also has no specification (according to docs, that means it'll include it all?). I am working with the quatroshapes now and starting to fill out the `alpha3_country_codes` with an array of all the country codes from http://www.geonames.org/countries/ . Is there a method to do `all` or is it even necessary to do that?

Would it make sense to make an 'all' option that has all the country codes listed or does it make sense to fill up the `alpha3_country_codes` array with all the countries? Example:

```
 'quattroshapes' => {
  'index_data' => true,
  'alpha3_country_codes' => [
    'AND', 'ARE', 'AFG',
    'ATG', 'AIA', 'ALB',
    'ARM', 'ANT', 'AGO',
    'ATA', 'ARG', 'ASM',
    'AUT', 'AUS', 'ABW',
    'ALA', 'AZE', 'BIH',
    'BRB', 'BGD', 'BEL',
    'BFA', 'BGR', 'BHR',
    'BDI', 'BEN', 'BLM',
    'BMU', 'BRN', 'BOL',
    'BES', 'BRA', 'BHS',
    ...
  ]
},
```

For the osm extracts array, I am doing a combination of mapzen and my own pbfs (is there a way to link to a local pbf ?).

**Comment by orangejulius** [comment]
Hey @rijvirajib,
To answer your first question: no you don't have to download the Geonames ZIP, it's downloaded automatically. :)

For your second: I had to read through the docs myself but there IS a way to [import all countries](https://github.com/pelias/geonames/blob/master/README.md#importing-data), but it looks like it's only available as a command line parameter. If you were looking for a place to contribute, allowing that same functionality to be used via the config file would be awesome. A flag like `importAllCountries` is probably a good way (in theory a country could some day have the 3 letter code `all`).

And finally, for OSM, the configuration works exactly like you want with [local files](https://github.com/pelias/openstreetmap#configuration). However, right now it only imports the first file (you can work around this by importing the files one at a time). We have a [ticket](https://github.com/pelias/openstreetmap/issues/55) to fix this that we haven't gotten to, so this would be another place where you could help out if you wanted.

Thanks!

**Comment by orangejulius** [comment]
We don't support Quattroshapes anymore, and I'm going to remove it from the Vagrant image soon, so I'm closing this issue. If you have any other questions or feedback don't hesitate to open a new issue!
