### ISSUE TITLE
vagrant angular demo - only search works?

### ISSUE THREAD

**Issue by hydrapolic** [pelias/vagrant#27]
After setting up the vagrant box and opening:
http://rawgit.com/pelias/demo/vagrant/index.html

all that works is the "search" method right? Because most of the time it tries to call suggest, but I get and error when loading that. Is "suggest" supposed to work on vagrant with the demo? Would it be possible to update the demo to use the new URL for search (and others, I don't know?):
http://localhost:3100/v1/search?text=london

**Comment by orangejulius** [comment]
Hey @hydrapolic,
This is a good catch. We've mostly deprecated the angular demo in favor of our [leaflet plugin](https://github.com/pelias/leaflet-geocoder) (demo [here])(http://pelias.github.io/leaflet-geocoder/)). We also recently released our first stable API which broke some old endpoints (suggest is now autocomplete for one). 

Were you looking for a place to contribute? We would gladly accept a PR swapping out the angular demo for our new leaflet plugin. But if not, we'll get to it soon now that we know about it!

**Comment by hydrapolic** [comment]
Thanks @orangejulius, that explains it! I'll play with the leaflet plugin, thanks!
