### ISSUE TITLE
The guest machine entered an invalid state error!

### ISSUE THREAD

**Issue by platomaniac** [pelias/vagrant#30]
I followed install guidelines from git hub and the sweet mapzen [tutorial](https://mapzen.com/blog/pelias-setup-tutorial) but consistently getting the following error.
-----------------------------------------------------------------------------------
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'poweroff' state. Please verify everything is configured
properly and try again

I am on a Windows 10 machine running Ubuntu 64 bit 12.04LTS latest Virtualbox. Same error occurs when I try to do it on a Virtual private server running Ubuntu 14.04.

The remote VPS detail: 
-----------------
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                6
On-line CPU(s) list:   0-5
Thread(s) per core:    1
Core(s) per socket:    6
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Stepping:              2
CPU MHz:               2399.996
BogoMIPS:              4799.99
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              15360K
NUMA node0 CPU(s):     0-5

In both cases (Ubuntu 12.04 running on Virtualbox in local Windows 10 or the remote VPS server running Ubuntu 14.04) when I start pelias using this 

PELIAS_VAGRANT_CFG="$(pwd)/pelias_settings.rb" vagrant up

I am consistently getting this error:
------------------------------------------------------------------------------------------------
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 3100 => 3100 (adapter 1)
    default: 9200 => 9200 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'poweroff' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

The primary issue for this error is that the provider you're using
is not properly configured. This is very rarely a Vagrant issue

**Comment by orangejulius** [comment]
Hey @platomaniac,
Have you been able to run any other vagrant instances? The simplest one might be the example listed on https://www.vagrantup.com/:

    vagrant init hashicorp/precise32
    vagrant up

If that does work, can you try what's suggested by Vagrant and run the `vagrant up` command with the Virtualbox GUI running so you can see any messages that appear on the virtual machine's screen? Those messages will probably be very helpful.

Thanks!

**Comment by ThreeScreenStudios** [comment]
I had this issue too - the problem is with VirtualBox and Windows. Uninstall VirtualBox, remove all of the virtual host adapters in the Device Manager and reinstall from the command line with virtualboxinstallerfile.exe -msiparams NETWORKTYPE=NDIS5 

Reboot, try again, and it hopefully should work!

From https://forums.virtualbox.org/viewtopic.php?f=6&t=70199

**Comment by riordan** [comment]
Any progress on this? Were you able to get the Vagrant install to work, @platomaniac.

(thanks for the assist @ThreeScreenStudios)

**Comment by platomaniac** [comment]
Guys! Thanks for the info but I am yet to try anything new with Vagrant. My workplace being a VPS without a GUI, the suggestion of @orangejulius does not fully help. The workload and deadlines were so harsh, I had to stop experimenting for a while. I suppose there is some issue with my Ubuntu 14.04 at the VPS that is messing up with Vagrant. 
@ThreeScreenStudios  Will try your suggestion on a local Windows machine and report back.

**Comment by orangejulius** [comment]
Hey @platomaniac,
We haven't heard anything in a while, so I'm going to close this issue. If you've uncovered anything new feel free to reopen this issue, and if you have any other problems don't hesitate to open another one! Thanks!
