### ISSUE TITLE
openaddress import example mislabled

### ISSUE THREAD

**Issue by easherma** [pelias/vagrant#34]
In the default settings example for openaddresses:

> 'openaddresses' => {
    'index_data' => true,
    'data_files' => [
      'us-ny-nyc'
    ]
  },

> 

The example doesn't seem to follow the naming conventions of the files on openaddress. 

'us-ny-nyc' should read 'us/ny/city_of_new_york' 

Examples:
[http://results.openaddresses.io/](url)

I confirmed this with Ian. I tried correcting the path and it appears that the URL may also not be parsed accurately. 

The complete zip seems to be working, though its in progress for me at the moment.

**Comment by riordan** [comment]
Great catch. We'll get it updated.
