### ISSUE TITLE
not so easy on Ubuntu 14

### ISSUE THREAD

**Issue by mtmail** [pelias/vagrant#4]
Of course I managed :) But to save others potentially an hour:

`apt-get install virtualbox vagrant` will install Vagrant 1.4.3 on Ubuntu 14.04 LTS (also tested 14.10). The recent Chef (at least vagrant-berkshelf which seems to be Berks 3.2.3) needs Vagrant ~>1.5.

There is no apt/deb package called `virtualbox`, the closest is `virtualbox-4.3` but only after added keys and sources listed in https://www.virtualbox.org/wiki/Linux_Downloads

**Comment by heffergm** [comment]
Thanks for the note. Unfortunately the details of the install process on linux seem to keep shifting. I'll make a note in the readme.
