### ISSUE TITLE
{"error":"Cannot read property 'toLowerCase' of undefined"} on default London query

### ISSUE THREAD

**Issue by msweetser** [pelias/vagrant#43]
I've set up Vagrant on Windows to set up the VirtualBox VM with the default pelias settings file.

However, I receive the following error when attempting to view http://localhost:3100/v1/search?text=London as per the README:

{"error":"Cannot read property 'toLowerCase' of undefined"}

**Comment by orangejulius** [comment]
Hey @msweetser,
Thanks for reporting this. It looks like it's probably a relatively small issue with our [api](https://github.com/pelias/api) code, but I don't remember having this exact issue. Still, can you try making sure you're using the most up to date API code? There are a few ways to do this, but if you don't mind, the most surefire way is to completely erase the vagrant image and start a new one with `vagrant destroy; vagrant up`. If it still happens, can you post the exact command you used to show that error and the full output of the command? Thanks! :star:

**Comment by geostarters** [comment]
Hello,
we have the same problem.
Yesterday we erase the vagrant image and start a new one and all works fine.
Then we import some data in format openaddress with Pelias import pipeline for OpenAddresses and then we obtain this error:
{"error":"Cannot read property 'toLowerCase' of undefined"}

This are some files of the openaddresses file:
LON,LAT,NUMBER,STREET,UNIT,CITY,DISTRICT,REGION,POSTCODE,ID
2.18034177,41.38730892,2,c. de Montanyans,,Barcelona,,,08003,
2.18001196,41.38741812,10,c. de Montanyans,,Barcelona,,,08003,
2.17991006,41.3874759,12,c. de Montanyans,,Barcelona,,,08003,

**Comment by orangejulius** [comment]
Hey @geostarters,
Thanks for confirming that this is happening! I haven't been able to reproduce it yet, so can you provide some more detailed info about exactly when/where this is happening?

When you get the error `{"error":"Cannot read property 'toLowerCase' of undefined"}`, is that part of a request to the API server?

If so can you post the full URL you hit and the full body of the response? Any chef logs would be helpful as well. Screenshots with lots of context (don't just show the part with the error, show lots of other output above/below it if you can) would also help! Thanks!

**Comment by msweetser** [comment]
Apologies for not replying - we moved on from Pelias for the time being but will revisit soon!  

We ended up using the updated directions to do a base installation, and were unable to reproduce the issue.  We believe it had to do with just using the wrong URL, but I don't have our notes at this point.
