### ISSUE TITLE
Vagrant-pelias - elasticsearch error SearchPhaseExecutionException

### ISSUE THREAD

**Issue by pawelchmara** [pelias/vagrant#51]
Hi,

I have run vagrant-project on Ubuntu 16.04 but unfortunatelly I get error when trying use reverse api:

Query:
`curl -s "localhost:3100/v1/reverse?&point.lat=51.118807&point.lon=17.041271&layers=address&size=1"`

Reply:
`{"geocoding":{"version":"0.1","attribution":"http://pelias.mapzen.com/v1/attribution","query":{"layers":["address"],"size":1,"private":false,"point.lat":51.118807,"point.lon":17.041271,"boundary.circle.radius":1,"boundary.circle.lat":51.118807,"boundary.circle.lon":17.041271,"querySize":1},"errors":**["SearchPhaseExecutionException[Failed to execute phase [query_fetch], all shards failed; shardFailures** {[AKfSlPa2QrS3SLv5TFrtqw][pelias][0]: SearchParseException[[pelias][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"bool\":{\"filter\":[{\"geo_distance\":{\"distance\":\"1km\",\"distance_type\":\"plane\",\"optimize_bbox\":\"indexed\",\"center_point\":{\"lat\":51.118807,\"lon\":17.041271}}}]}},\"size\":1,\"track_scores\":true,\"sort\":[\"_score\",{\"_geo_distance\":{\"order\":\"asc\",\"distance_type\":\"plane\",\"center_point\":{\"lat\":51.118807,\"lon\":17.041271}}}]}]]]; nested: QueryParsingException[[pelias] bool query does not support [filter]]; }]"],"engine":{"name":"Pelias","author":"Mapzen","version":"1.0"},"timestamp":1468218715236},"type":"FeatureCollection","features":[]}vagrant@pelias`

Some more information about elasticsearch version and status:

```
curl -s 'http://localhost:9200/_cluster/health?pretty=true'
{
  "cluster_name" : "elasticsearch",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 1,
  "active_shards" : 1,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0
}

```

```
curl -s 'http://localhost:9200'
{
  "status" : 200,
  "name" : "pelias",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.7.3",
    "build_hash" : "05d4530971ef0ea46d0f4fa6ee64dbc8df659682",
    "build_timestamp" : "2015-10-15T09:14:17Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

Vagrant configuration file:

```
Vagrant.configure('2') do |config|
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = 'cookbooks'

    chef.json = {
      'pelias' => {
        'schema' => {
          'create_index' => true
        },
        'openaddresses' => {
          'index_data' => false,
          'data_dir' => '/opt/pelias/data/openaddresses',
          'data_files' => [
            'dolnoslaskie.csv'
          ]
        },
        'geonames' => {
          'index_data' => false,
          'alpha2_country_codes' => [
            'GB'
          ]
        },
        'osm' => {
          'index_data' => true,
          'admin_lookup' => false,
          'extracts' => { http://download.geofabrik.de/europe/poland/dolnoslaskie-latest.osm.pbf'
          }
        }
      }
    }

    chef.run_list = [
      'recipe[pelias::default]'
    ]
  end
end
```

I would just like to mention that i.e. query http://localhost:3100/v1/autocomplete?text=Wroclaw works proper.

Thanks for help!

**Comment by orangejulius** [comment]
I think this is our fault, we've let the Vagrant image stagnate a bit and it hasn't been touched for the Elasticsearch 2 upgrade, so I think some of our queries no longer work on the Vagrant image, since all our code assumes Elasticsearch 2, but the Vagrant image is still on 1.7. If you want to try to fiddle with the version numbers in the config and relaunch the image, it may work, and we'd be very thankful for any info on how things go. But if not, we'll get to it at some point.

**Comment by dianashk** [comment]
The vagrant repo has been deprecated in favor of pelias/dockerfiles.
