### ISSUE TITLE
Make repo branches configurable

### ISSUE THREAD

**Issue by dianashk** [pelias/vagrant#9]
It would be really helpful if we could easily specify a branch name in an external config file that would override the values specified here: https://github.com/pelias/vagrant/blob/4bccbdf42889dbc728fbadfad9226ab2052ba5c0/cookbooks/pelias/attributes/default.rb#L25

The idea being that when testing a branch of api, for example, we can spin up vagrant with the code from that branch and then run acceptance tests against it.

**Comment by heffergm** [comment]
You can already do this. See the readme, specifically references to pelias_config.rb. 

https://github.com/pelias/vagrant/blob/master/README.md#getting-started

**Comment by heffergm** [comment]
For reference, my setup:

```json
Vagrant.configure('2') do |config|
  config.vm.provision :chef_solo do |chef|
    chef.json = {
      'pelias' => {
        'api' => {
          'revision' => 'master'
        },
        'schema' => {
          'create_index' => true,
          'revision' => 'master'
        },
        'geonames' => {
          'index_data' => true,
          'revision' => 'master',
          'alpha2_country_codes' => [
            'GB'
          ]
        },
        'quattroshapes' => {
          'index_data' => true,
          'revision' => 'master',
          'alpha3_country_codes' => [
            'GBR'
          ]
        },
        'osm' => {
          'index_data' => true,
          'revision' => 'master',
          'extracts' => {
            'london' => 'https://s3.amazonaws.com/metro-extracts.mapzen.com/london_england.osm.pbf'
          }
        }
      }
    }

    chef.run_list = [
      'recipe[pelias::default]'
    ]
  end
end
```

**Comment by dianashk** [comment]
Ah sorry, thought that was only in reference to the data. Thanks for clarifying.
